import type { Activity, ActivityId } from './types';

export const ACTIVITIES: Record<ActivityId, Activity> = {
  // ─── Tier 1 — F2P ───────────────────────────────────────────────────────────
  // ── Woodcutting ladder ──
  wc_trees: {
    id: 'wc_trees', name: 'Woodcutting — Normal Trees', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { woodcutting: 1 },
    gpPerHour: 900, suspicionPerHour: 0.8,
    baseDetectionRatePerTick: 0.0004,
    xpPerHour: { woodcutting: 9000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Available from the start.',
    flavorText: 'Cut log. Drop log. Repeat. The most boring possible bot — and the safest.',
  },
  wc_oaks: {
    id: 'wc_oaks', name: 'Woodcutting — Oak Trees', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { woodcutting: 15 },
    gpPerHour: 1800, suspicionPerHour: 1.2,
    baseDetectionRatePerTick: 0.0005,
    xpPerHour: { woodcutting: 22000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Woodcutting 15.',
    flavorText: 'Slow but safe. Oaks near the bank. Very human-looking... probably.',
  },
  wc_willows: {
    id: 'wc_willows', name: 'Woodcutting — Willows', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { woodcutting: 30 },
    gpPerHour: 3200, suspicionPerHour: 1.4,
    baseDetectionRatePerTick: 0.0006,
    xpPerHour: { woodcutting: 40000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Woodcutting 30.',
    flavorText: 'Draynor willows. Six bots in a circle. Nobody suspects a thing.',
  },
  wc_maples: {
    id: 'wc_maples', name: 'Woodcutting — Maples', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { woodcutting: 45 },
    gpPerHour: 5200, suspicionPerHour: 1.6,
    baseDetectionRatePerTick: 0.0007,
    xpPerHour: { woodcutting: 52000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Woodcutting 45.',
    flavorText: 'Seers Village preset 2. Industry standard.',
  },
  wc_yews: {
    id: 'wc_yews', name: 'Woodcutting — Yew Trees', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { woodcutting: 60 },
    gpPerHour: 8500, suspicionPerHour: 1.8,
    baseDetectionRatePerTick: 0.0008,
    xpPerHour: { woodcutting: 65000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Woodcutting 60.',
    flavorText: 'The classic F2P bot spot. Jagex has seen a million of these.',
  },

  // ── Fishing ladder ──
  fish_shrimp: {
    id: 'fish_shrimp', name: 'Fishing — Shrimp', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { fishing: 1 },
    gpPerHour: 320, suspicionPerHour: 0.7,
    baseDetectionRatePerTick: 0.0003,
    xpPerHour: { fishing: 7000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Available from the start.',
    flavorText: 'Lumbridge swamp small net. Where every account begins. And where some never leave.',
  },
  fish_sardines: {
    id: 'fish_sardines', name: 'Fishing — Sardines & Herring', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { fishing: 5 },
    gpPerHour: 720, suspicionPerHour: 0.9,
    baseDetectionRatePerTick: 0.0004,
    xpPerHour: { fishing: 12000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Fishing 5.',
    flavorText: 'Bait fishing rod. Draynor docks. The bot eats the worms instead of using them. Once.',
  },
  fish_anchovies: {
    id: 'fish_anchovies', name: 'Fishing — Anchovies', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { fishing: 15 },
    gpPerHour: 1300, suspicionPerHour: 1.0,
    baseDetectionRatePerTick: 0.0005,
    xpPerHour: { fishing: 18000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Fishing 15.',
    flavorText: 'Anchovy pizza ingredients. Quietly profitable. The dark wizards near Draynor are a problem.',
  },
  fish_trout_salmon: {
    id: 'fish_trout_salmon', name: 'Fishing — Trout & Salmon (Fly)', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { fishing: 20 },
    gpPerHour: 2400, suspicionPerHour: 1.2,
    baseDetectionRatePerTick: 0.0006,
    xpPerHour: { fishing: 28000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Fishing 20.',
    flavorText: 'Barbarian Village fly fishing. Stand still. Click. Stand still. Click.',
  },
  fish_lobsters: {
    id: 'fish_lobsters', name: 'Fishing — Lobsters', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { fishing: 40 },
    gpPerHour: 7000, suspicionPerHour: 1.5,
    baseDetectionRatePerTick: 0.0006,
    xpPerHour: { fishing: 30000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Fishing 40.',
    flavorText: 'Karamja dock bots. A tale as old as time.',
  },
  fish_bass: {
    id: 'fish_bass', name: 'Fishing — Bass', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { fishing: 46 },
    gpPerHour: 5400, suspicionPerHour: 1.6,
    baseDetectionRatePerTick: 0.0007,
    xpPerHour: { fishing: 34000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Fishing 46.',
    flavorText: 'Catherby pier. Big nets. Bigger lies on the player\'s achievement diary.',
  },
  fish_tuna_swordfish: {
    id: 'fish_tuna_swordfish', name: 'Fishing — Tuna & Swordfish', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { fishing: 50 },
    gpPerHour: 6200, suspicionPerHour: 1.7,
    baseDetectionRatePerTick: 0.0008,
    xpPerHour: { fishing: 38000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Fishing 50.',
    flavorText: 'Catherby docks. Same harpoon, same animation, eight hours straight.',
  },
  fish_sharks: {
    id: 'fish_sharks', name: 'Fishing — Sharks', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { fishing: 76 },
    gpPerHour: 11000, suspicionPerHour: 2.0,
    baseDetectionRatePerTick: 0.0010,
    xpPerHour: { fishing: 30000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Fishing 76.',
    flavorText: 'Higher value, higher risk. Worth it if your break handler is good.',
  },

  // ── Mining ladder ──
  mine_tin: {
    id: 'mine_tin', name: 'Mining — Tin & Copper', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { mining: 1 },
    gpPerHour: 550, suspicionPerHour: 0.9,
    baseDetectionRatePerTick: 0.0004,
    xpPerHour: { mining: 8000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Available from the start.',
    flavorText: 'Power-mining bronze. The pickaxe is older than the player.',
  },
  mine_clay: {
    id: 'mine_clay', name: 'Mining — Soft Clay', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { mining: 1 },
    gpPerHour: 1700, suspicionPerHour: 1.2,
    baseDetectionRatePerTick: 0.0005,
    xpPerHour: { mining: 12000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Available from the start.',
    flavorText: 'Varrock west. Dip in fountain. Soft clay sells for double. The bot loves a good loop.',
  },
  mine_rune_essence: {
    id: 'mine_rune_essence', name: 'Mining — Rune Essence', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { mining: 1 },
    gpPerHour: 700, suspicionPerHour: 1.0,
    baseDetectionRatePerTick: 0.0005,
    xpPerHour: { mining: 7500 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Available from the start. Aubury teleport loop.',
    flavorText: 'Aubury teleport, mine 28, bank, repeat. The most predictable click pattern in the game.',
  },
  mine_iron: {
    id: 'mine_iron', name: 'Mining — Iron Ore', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { mining: 15 },
    gpPerHour: 3200, suspicionPerHour: 1.6,
    baseDetectionRatePerTick: 0.0007,
    xpPerHour: { mining: 40000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Mining 15.',
    flavorText: '3 rocks. Power mine. Repeat. The bot is indistinguishable from a real player.',
  },
  mine_silver: {
    id: 'mine_silver', name: 'Mining — Silver Ore', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { mining: 20 },
    gpPerHour: 3800, suspicionPerHour: 1.5,
    baseDetectionRatePerTick: 0.0007,
    xpPerHour: { mining: 18000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Mining 20.',
    flavorText: 'Al Kharid silver rocks. Jewellery market. Quietly profitable.',
  },
  mine_coal: {
    id: 'mine_coal', name: 'Mining — Coal', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { mining: 30 },
    gpPerHour: 4800, suspicionPerHour: 1.8,
    baseDetectionRatePerTick: 0.0009,
    xpPerHour: { mining: 22000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Mining 30.',
    flavorText: 'Dwarven mines are always full of bots. Yours will fit right in.',
  },
  mine_gold: {
    id: 'mine_gold', name: 'Mining — Gold Ore', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { mining: 40 },
    gpPerHour: 5400, suspicionPerHour: 1.7,
    baseDetectionRatePerTick: 0.0008,
    xpPerHour: { mining: 32000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Mining 40.',
    flavorText: 'Crafting Guild has security cameras now? Run them anyway.',
  },
  mine_mithril: {
    id: 'mine_mithril', name: 'Mining — Mithril Ore', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { mining: 55 },
    gpPerHour: 7200, suspicionPerHour: 2.0,
    baseDetectionRatePerTick: 0.0009,
    xpPerHour: { mining: 24000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Mining 55.',
    flavorText: 'Slow rocks. Long respawn. The bot stares at the wall in between. Disturbing.',
  },
  mine_adamantite: {
    id: 'mine_adamantite', name: 'Mining — Adamantite Ore', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { mining: 70 },
    gpPerHour: 9500, suspicionPerHour: 2.2,
    baseDetectionRatePerTick: 0.0010,
    xpPerHour: { mining: 18000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Mining 70.',
    flavorText: 'World hop, mine 1, world hop. The script knows every world by heart.',
  },
  mine_runite_wilderness: {
    id: 'mine_runite_wilderness', name: 'Mining — Runite (Wilderness)', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { mining: 85 },
    gpPerHour: 14000, suspicionPerHour: 2.8,
    baseDetectionRatePerTick: 0.0014,
    xpPerHour: { mining: 22000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Mining 85. Wilderness — PKers and Jagex are equally hostile.',
    flavorText: 'Level 46 wilderness. Runite ore. The bot will die. The bot will be replaced. The bot will mine again.',
  },

  // ── Smithing ladder ──
  smith_bronze_bars: {
    id: 'smith_bronze_bars', name: 'Smithing — Bronze Bar Smelting', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { smithing: 1 },
    gpPerHour: 800, suspicionPerHour: 1.0,
    baseDetectionRatePerTick: 0.0005,
    xpPerHour: { smithing: 6000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Available from the start.',
    flavorText: 'Tin + copper = bronze. The most basic smelting loop. The bot is proud.',
  },
  smith_iron_bars: {
    id: 'smith_iron_bars', name: 'Smithing — Iron Bar Smelting', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { smithing: 15 },
    gpPerHour: 2200, suspicionPerHour: 1.4,
    baseDetectionRatePerTick: 0.0006,
    xpPerHour: { smithing: 18000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Smithing 15.',
    flavorText: 'Bank → furnace → bank. Half the bars fail. Still profit.',
  },
  smith_steel_bars: {
    id: 'smith_steel_bars', name: 'Smithing — Steel Bar Smelting', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { smithing: 30 },
    gpPerHour: 3200, suspicionPerHour: 1.5,
    baseDetectionRatePerTick: 0.0007,
    xpPerHour: { smithing: 28000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Smithing 30. 2 coal + 1 iron per bar.',
    flavorText: 'Edgeville furnace. Coal eater. The script optimised this five years ago.',
  },
  smith_iron_platebodies: {
    id: 'smith_iron_platebodies', name: 'Smithing — Iron Platebodies', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { smithing: 33 },
    gpPerHour: 3400, suspicionPerHour: 1.6,
    baseDetectionRatePerTick: 0.0007,
    xpPerHour: { smithing: 36000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Smithing 33. Anvil work in Varrock west.',
    flavorText: 'Five iron bars. One platebody. Alch fodder for high-magic accounts.',
  },
  smith_gold_bars: {
    id: 'smith_gold_bars', name: 'Smithing — Gold Bar Smelting', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { smithing: 40 },
    gpPerHour: 2600, suspicionPerHour: 1.4,
    baseDetectionRatePerTick: 0.0006,
    xpPerHour: { smithing: 22000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Smithing 40.',
    flavorText: 'Goldsmith gauntlets help. The bot doesn\'t have them. The bot doesn\'t care.',
  },
  smith_mithril_bars: {
    id: 'smith_mithril_bars', name: 'Smithing — Mithril Bar Smelting', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { smithing: 50 },
    gpPerHour: 5500, suspicionPerHour: 1.7,
    baseDetectionRatePerTick: 0.0008,
    xpPerHour: { smithing: 36000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Smithing 50. 4 coal + 1 mithril per bar.',
    flavorText: 'Eats coal like a furnace. Which is what it is.',
  },
  smith_adamant_bars: {
    id: 'smith_adamant_bars', name: 'Smithing — Adamant Bar Smelting', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { smithing: 70 },
    gpPerHour: 7200, suspicionPerHour: 1.9,
    baseDetectionRatePerTick: 0.0009,
    xpPerHour: { smithing: 42000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Smithing 70. 6 coal + 1 adamant per bar.',
    flavorText: 'The coal supply chain is the real bottleneck. Set up a second bot.',
  },

  // ── Runecrafting ladder ──
  rc_air_runes: {
    id: 'rc_air_runes', name: 'Runecrafting — Air Runes', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { runecrafting: 1 },
    gpPerHour: 1600, suspicionPerHour: 1.5,
    baseDetectionRatePerTick: 0.0007,
    xpPerHour: { runecrafting: 9000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Available from the start.',
    flavorText: 'Falador → Air altar → Falador. The route is burned into the script.',
  },
  rc_mind_runes: {
    id: 'rc_mind_runes', name: 'Runecrafting — Mind Runes', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { runecrafting: 2 },
    gpPerHour: 1900, suspicionPerHour: 1.5,
    baseDetectionRatePerTick: 0.0007,
    xpPerHour: { runecrafting: 9500 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Runecrafting 2.',
    flavorText: 'Goblin Village → Mind altar. The route avoids three goblins. Most days.',
  },
  rc_water_runes: {
    id: 'rc_water_runes', name: 'Runecrafting — Water Runes', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { runecrafting: 5 },
    gpPerHour: 2200, suspicionPerHour: 1.5,
    baseDetectionRatePerTick: 0.0007,
    xpPerHour: { runecrafting: 11000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Runecrafting 5.',
    flavorText: 'Lumbridge swamp shortcut. The bot fell in the water once. It learned.',
  },
  rc_earth_runes: {
    id: 'rc_earth_runes', name: 'Runecrafting — Earth Runes', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { runecrafting: 9 },
    gpPerHour: 2800, suspicionPerHour: 1.6,
    baseDetectionRatePerTick: 0.0008,
    xpPerHour: { runecrafting: 14000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Runecrafting 9.',
    flavorText: 'Varrock east bank → Earth altar. Half the screen is bots running the same path.',
  },
  rc_fire_runes: {
    id: 'rc_fire_runes', name: 'Runecrafting — Fire Runes', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { runecrafting: 14 },
    gpPerHour: 3400, suspicionPerHour: 1.7,
    baseDetectionRatePerTick: 0.0008,
    xpPerHour: { runecrafting: 17000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Runecrafting 14.',
    flavorText: 'Duel Arena → Fire altar. The desert dehydration is a feature, not a bug.',
  },
  rc_body_runes: {
    id: 'rc_body_runes', name: 'Runecrafting — Body Runes', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { runecrafting: 20 },
    gpPerHour: 3800, suspicionPerHour: 1.7,
    baseDetectionRatePerTick: 0.0008,
    xpPerHour: { runecrafting: 22000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Runecrafting 20.',
    flavorText: 'Barbarian Village → Body altar. The fastest F2P run. The bot has it down to seconds.',
  },

  // ── Magic ──
  magic_low_alch: {
    id: 'magic_low_alch', name: 'Magic — Low Alchemy Loop', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { magic: 21 },
    gpPerHour: 2200, suspicionPerHour: 1.3,
    baseDetectionRatePerTick: 0.0006,
    xpPerHour: { magic: 32000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Magic 21.',
    flavorText: 'Click. Alch. Click. Alch. The training wheels for the high alch grind.',
  },
  magic_telegrab_wines: {
    id: 'magic_telegrab_wines', name: 'Magic — Wine of Zamorak Telegrab', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { magic: 33 },
    gpPerHour: 6500, suspicionPerHour: 2.1,
    baseDetectionRatePerTick: 0.0010,
    xpPerHour: { magic: 38000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Magic 33. Telekinetic Grab from Chaos Temple.',
    flavorText: 'Snatch wine off the altar before the monks aggro. The bot mistimes it 2% of the time.',
  },
  magic_high_alch_plates: {
    id: 'magic_high_alch_plates', name: 'Magic — High Alch Iron Plates', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { magic: 55 },
    gpPerHour: 4500, suspicionPerHour: 1.6,
    baseDetectionRatePerTick: 0.0007,
    xpPerHour: { magic: 78000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Magic 55. Pair with smithed iron platebodies.',
    flavorText: 'Iron platebody → 1,200 gp. Nat rune → 200 gp. Math. Mostly.',
  },

  // ── Production / Misc ──
  tan_cowhides: {
    id: 'tan_cowhides', name: 'Cowhide Tanning Loop', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: {},
    gpPerHour: 4500, suspicionPerHour: 1.4,
    baseDetectionRatePerTick: 0.0006,
    xpPerHour: {},
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'No skill requirements. Buy hides → tan in Al Kharid → resell.',
    flavorText: 'Bank → tanner → bank. The bot has no skill. It just has GP/hr.',
  },
  stronghold_clearout: {
    id: 'stronghold_clearout', name: 'Stronghold of Security Clear-Out', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 1 },
    gpPerHour: 1100, suspicionPerHour: 1.0,
    baseDetectionRatePerTick: 0.0005,
    xpPerHour: { attack: 4000, strength: 4000, defence: 3000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Available from the start. Reset bot every cycle for the 10k bonus.',
    flavorText: 'Walk to the gate. Answer the questions. Grab the 10k. Suicide. New bot. Repeat.',
  },

  // ── Combat ladder ──
  combat_chickens: {
    id: 'combat_chickens', name: 'Combat — Chickens', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 1 },
    gpPerHour: 220, suspicionPerHour: 0.6,
    baseDetectionRatePerTick: 0.0003,
    xpPerHour: { attack: 1500, strength: 1500, defence: 1000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Available from the start. Feathers + bones.',
    flavorText: 'The training wheels. No one watches the chicken pen. No one.',
  },
  combat_giant_rats: {
    id: 'combat_giant_rats', name: 'Combat — Giant Rats', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 1 },
    gpPerHour: 280, suspicionPerHour: 0.7,
    baseDetectionRatePerTick: 0.0003,
    xpPerHour: { attack: 1800, strength: 1800, defence: 1200 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Available from the start. Lumbridge swamp.',
    flavorText: 'Rat tail. Rat tail. Rat tail. The bot collects them like trophies.',
  },
  combat_men: {
    id: 'combat_men', name: 'Combat — Men & Women', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 1 },
    gpPerHour: 850, suspicionPerHour: 1.5,
    baseDetectionRatePerTick: 0.0006,
    xpPerHour: { attack: 2200, strength: 2200, defence: 1500 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Available from the start. Coins + bones.',
    flavorText: 'Murdering NPCs in Varrock square at 3am. Surely no one will notice.',
  },
  combat_monks: {
    id: 'combat_monks', name: 'Combat — Monks of Edgeville', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 1 },
    gpPerHour: 350, suspicionPerHour: 0.8,
    baseDetectionRatePerTick: 0.0004,
    xpPerHour: { attack: 2400, strength: 2400, defence: 1800, prayer: 1200 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Available from the start. Heals you when not hostile.',
    flavorText: 'Monks heal you back. The bot abuses pacifism. The bot has no soul.',
  },
  combat_goblins: {
    id: 'combat_goblins', name: 'Combat — Goblins', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 1 },
    gpPerHour: 480, suspicionPerHour: 0.9,
    baseDetectionRatePerTick: 0.0004,
    xpPerHour: { attack: 2500, strength: 2500, defence: 1800 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Available from the start.',
    flavorText: 'Lumbridge → goblin → Lumbridge. The most pathetic warrior arc.',
  },
  combat_giant_frogs: {
    id: 'combat_giant_frogs', name: 'Combat — Giant Frogs', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 5 },
    gpPerHour: 600, suspicionPerHour: 1.0,
    baseDetectionRatePerTick: 0.0005,
    xpPerHour: { attack: 3200, strength: 3200, defence: 2400 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Attack 5. Lumbridge swamp.',
    flavorText: 'Big frogs. Bigger XP. The swamp is full of bots and the occasional real player.',
  },
  combat_cows: {
    id: 'combat_cows', name: 'Combat — Cows', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 1 },
    gpPerHour: 600, suspicionPerHour: 1.4,
    baseDetectionRatePerTick: 0.0006,
    xpPerHour: { attack: 3000, strength: 3000, defence: 2000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Available from the start. Hides + bones.',
    flavorText: 'Every account starts here. Even the non-bots.',
  },
  combat_imps: {
    id: 'combat_imps', name: 'Combat — Imps', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 7 },
    gpPerHour: 1200, suspicionPerHour: 1.3,
    baseDetectionRatePerTick: 0.0006,
    xpPerHour: { attack: 4000, strength: 4000, defence: 2500 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Attack 7. Beads + low-tier drops.',
    flavorText: 'Tiny demons that teleport. So does your bot — straight to the next imp.',
  },
  combat_minotaurs: {
    id: 'combat_minotaurs', name: 'Combat — Minotaurs', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 15, strength: 15, defence: 10 },
    gpPerHour: 1900, suspicionPerHour: 1.4,
    baseDetectionRatePerTick: 0.0006,
    xpPerHour: { attack: 5500, strength: 5500, defence: 4000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Combat 15+. Stronghold of Security level 1.',
    flavorText: 'Iron arrow drops fund a Ranged bot. The pipeline is alive.',
  },
  combat_dark_wizards: {
    id: 'combat_dark_wizards', name: 'Combat — Dark Wizards', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 14 },
    gpPerHour: 2800, suspicionPerHour: 1.5,
    baseDetectionRatePerTick: 0.0007,
    xpPerHour: { attack: 5000, strength: 5000, defence: 3500 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Attack 14. Talisman drops south of Varrock.',
    flavorText: 'Talismans for the runecrafting bots. Vertical integration.',
  },
  combat_flesh_crawlers: {
    id: 'combat_flesh_crawlers', name: 'Combat — Flesh Crawlers', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 20, strength: 20, defence: 15 },
    gpPerHour: 1700, suspicionPerHour: 1.1,
    baseDetectionRatePerTick: 0.0005,
    xpPerHour: { attack: 14000, strength: 14000, defence: 9000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Combat 20+. Stronghold of Security level 2 — best AFK XP.',
    flavorText: 'Stack three of them in a corner. Auto-retaliate. Eight hour trip.',
  },
  combat_zombies: {
    id: 'combat_zombies', name: 'Combat — Varrock Sewer Zombies', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 22, strength: 22, defence: 15 },
    gpPerHour: 2100, suspicionPerHour: 1.4,
    baseDetectionRatePerTick: 0.0006,
    xpPerHour: { attack: 7000, strength: 7000, defence: 5000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Combat 22+. Varrock sewers.',
    flavorText: 'Smelly. Profitable. The bot doesn\'t notice the smell.',
  },
  combat_skeletons: {
    id: 'combat_skeletons', name: 'Combat — Skeletons', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 22, strength: 22, defence: 18 },
    gpPerHour: 2400, suspicionPerHour: 1.5,
    baseDetectionRatePerTick: 0.0007,
    xpPerHour: { attack: 7500, strength: 7500, defence: 5500 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Combat 22+. Varrock sewers / Edgeville dungeon.',
    flavorText: 'Crumble Undead them if you have it. Or just whack them. The bones add up.',
  },
  combat_giant_spiders: {
    id: 'combat_giant_spiders', name: 'Combat — Giant Spiders', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 30, strength: 30, defence: 25 },
    gpPerHour: 3200, suspicionPerHour: 1.6,
    baseDetectionRatePerTick: 0.0007,
    xpPerHour: { attack: 9000, strength: 9000, defence: 6500 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Combat 30+. Varrock sewers.',
    flavorText: 'They poison. The bot doesn\'t care. The bot has 200 antipoisons in the bank.',
  },
  combat_hobgoblins: {
    id: 'combat_hobgoblins', name: 'Combat — Hobgoblins', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 25, strength: 25, defence: 20 },
    gpPerHour: 2400, suspicionPerHour: 1.5,
    baseDetectionRatePerTick: 0.0007,
    xpPerHour: { attack: 6000, strength: 6000, defence: 4000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Combat 25+. Limpwurt roots.',
    flavorText: 'The intermediate grind. Limpwurts pay the bills until giants are unlocked.',
  },
  combat_hill_giants: {
    id: 'combat_hill_giants', name: 'Combat — Hill Giants', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 40, strength: 40, defence: 40 },
    gpPerHour: 9000, suspicionPerHour: 2.0,
    baseDetectionRatePerTick: 0.0010,
    xpPerHour: { attack: 8000, strength: 8000, defence: 6000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Combat 40+.',
    flavorText: 'Big bones + limpwurt roots. Real money. Real risk.',
  },
  combat_black_knights: {
    id: 'combat_black_knights', name: 'Combat — Black Knights', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 45, strength: 45, defence: 45 },
    gpPerHour: 6800, suspicionPerHour: 1.9,
    baseDetectionRatePerTick: 0.0009,
    xpPerHour: { attack: 9000, strength: 9000, defence: 7000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Combat 45+. Black Knights\' Fortress.',
    flavorText: 'Steel armour drops. Alch fodder. The fortress door doesn\'t lock.',
  },
  combat_ankou: {
    id: 'combat_ankou', name: 'Combat — Ankou', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 50, strength: 50, defence: 45 },
    gpPerHour: 7800, suspicionPerHour: 2.0,
    baseDetectionRatePerTick: 0.0010,
    xpPerHour: { attack: 11000, strength: 11000, defence: 8500 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Combat 50+. Stronghold of Security level 4.',
    flavorText: 'Death incarnate. Drops death runes. The bot is unbothered.',
  },
  combat_lesser_demons: {
    id: 'combat_lesser_demons', name: 'Combat — Lesser Demons', tier: 1,
    requiresMembers: false, requiresPremium: false,
    skillRequirements: { attack: 60, strength: 60, defence: 50, ranged: 60 },
    gpPerHour: 9500, suspicionPerHour: 2.2,
    baseDetectionRatePerTick: 0.0011,
    xpPerHour: { attack: 11000, strength: 11000, defence: 8000, ranged: 9000 },
    unlockCost: 0, teamSize: 1,
    unlockDescription: 'Requires Combat 60+ and Ranged 60.',
    flavorText: 'Karamja volcano top floor. Hash drop tables, but the bot doesn\'t mind waiting.',
  },

  // ─── Tier 2 — Members ───────────────────────────────────────────────────────
  green_dragons: {
    id: 'green_dragons', name: 'Green Dragon Farming', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { attack: 70, strength: 70, defence: 70 },
    gpPerHour: 35000, suspicionPerHour: 3.8,
    baseDetectionRatePerTick: 0.0018,
    xpPerHour: { attack: 15000, strength: 15000, defence: 15000 },
    unlockCost: 15000, teamSize: 1,
    unlockDescription: 'Requires Members + Combat 70+. Auto-purchases Anti-Dragon Shield.',
    flavorText: 'Wilderness dragons. PKers are the least of your problems.',
  },
  blast_furnace: {
    id: 'blast_furnace', name: 'Blast Furnace — Steel Bars', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { smithing: 30 },
    gpPerHour: 28000, suspicionPerHour: 3.2,
    baseDetectionRatePerTick: 0.0015,
    xpPerHour: { smithing: 55000 },
    unlockCost: 20000, teamSize: 1,
    unlockDescription: 'Requires Members + Smithing 30. Blast Furnace Script recommended.',
    flavorText: 'The Blast Furnace minigame. Your bot looks suspicious because it never talks.',
  },
  nmz_afk: {
    id: 'nmz_afk', name: 'Nightmare Zone — AFK Melee', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { attack: 75, strength: 75, defence: 75 },
    gpPerHour: 20000, suspicionPerHour: 2.8,
    baseDetectionRatePerTick: 0.0012,
    xpPerHour: { attack: 25000, strength: 25000, defence: 25000 },
    unlockCost: 8000, teamSize: 1,
    unlockDescription: 'Requires Members + Combat 75+ + NMZ Access (8,000 GP one-time).',
    flavorText: 'AFK training paradise. Your bot sits in a corner absorbing hits. Natural.',
  },
  nature_runes: {
    id: 'nature_runes', name: 'Nature Rune Crafting', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { runecrafting: 44 },
    gpPerHour: 25000, suspicionPerHour: 3.5,
    baseDetectionRatePerTick: 0.0016,
    xpPerHour: { runecrafting: 28000 },
    unlockCost: 12000, teamSize: 1,
    unlockDescription: 'Requires Members + Runecrafting 44.',
    flavorText: 'Abyss running. High traffic area. Try not to stand out.',
  },
  thieving_blackjack: {
    id: 'thieving_blackjack', name: 'Thieving — Blackjacking', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { thieving: 65 },
    gpPerHour: 40000, suspicionPerHour: 4.5,
    baseDetectionRatePerTick: 0.0022,
    xpPerHour: { thieving: 200000 },
    unlockCost: 18000, teamSize: 1,
    unlockDescription: 'Requires Members + Thieving 65. High XP, high suspicion.',
    flavorText: 'Blackjacking bandits in Pollnivneach. The click pattern is... robotic.',
  },

  // ─── Tier 2 — Members Combat / Slayer ───────────────────────────────────────
  combat_moss_giants: {
    id: 'combat_moss_giants', name: 'Combat — Moss Giants', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { attack: 42, strength: 42, defence: 42 },
    gpPerHour: 18000, suspicionPerHour: 2.6,
    baseDetectionRatePerTick: 0.0013,
    xpPerHour: { attack: 14000, strength: 14000, defence: 11000 },
    unlockCost: 5000, teamSize: 1,
    unlockDescription: 'Requires Members + Combat 42+. Brimhaven dungeon.',
    flavorText: 'Big bones. Big rune drops. The bot loots through the moss without flinching.',
  },
  slayer_crawling_hands: {
    id: 'slayer_crawling_hands', name: 'Slayer — Crawling Hands', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { slayer: 5, attack: 20, strength: 20 },
    gpPerHour: 22000, suspicionPerHour: 2.7,
    baseDetectionRatePerTick: 0.0013,
    xpPerHour: { slayer: 6000, attack: 8000, strength: 8000 },
    unlockCost: 6000, teamSize: 1,
    unlockDescription: 'Requires Members + Slayer 5. Slayer Tower ground floor.',
    flavorText: 'Disembodied hands drop gold rings. The bot wears them all. Suspicious.',
  },
  slayer_banshees: {
    id: 'slayer_banshees', name: 'Slayer — Banshees', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { slayer: 15, attack: 30, defence: 25 },
    gpPerHour: 24000, suspicionPerHour: 2.8,
    baseDetectionRatePerTick: 0.0014,
    xpPerHour: { slayer: 9000, attack: 11000, defence: 9000 },
    unlockCost: 8000, teamSize: 1,
    unlockDescription: 'Requires Members + Slayer 15. Earmuffs needed (auto-equipped).',
    flavorText: 'The bot has earmuffs. The bot does not need ears. The bot is fine.',
  },
  slayer_pyrefiends: {
    id: 'slayer_pyrefiends', name: 'Slayer — Pyrefiends', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { slayer: 30, attack: 40, defence: 35 },
    gpPerHour: 26000, suspicionPerHour: 2.9,
    baseDetectionRatePerTick: 0.0014,
    xpPerHour: { slayer: 12000, attack: 13000, defence: 10000 },
    unlockCost: 10000, teamSize: 1,
    unlockDescription: 'Requires Members + Slayer 30.',
    flavorText: 'Fire demons in the Slayer Tower basement. Drop rates favour the patient. Like a script.',
  },
  slayer_basilisks: {
    id: 'slayer_basilisks', name: 'Slayer — Basilisks', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { slayer: 40, attack: 50, defence: 50 },
    gpPerHour: 28000, suspicionPerHour: 3.0,
    baseDetectionRatePerTick: 0.0015,
    xpPerHour: { slayer: 15000, attack: 16000, defence: 13000 },
    unlockCost: 12000, teamSize: 1,
    unlockDescription: 'Requires Members + Slayer 40. Fremennik Slayer Cave. Mirror shield needed.',
    flavorText: 'Look directly at the basilisk: -100 stats. The bot scripts a mirror shield equip. Always.',
  },
  slayer_bloodvelds: {
    id: 'slayer_bloodvelds', name: 'Slayer — Bloodvelds', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { slayer: 50, attack: 60, defence: 60 },
    gpPerHour: 32000, suspicionPerHour: 3.1,
    baseDetectionRatePerTick: 0.0015,
    xpPerHour: { slayer: 22000, attack: 22000, defence: 18000, hitpoints: 18000 },
    unlockCost: 14000, teamSize: 1,
    unlockDescription: 'Requires Members + Slayer 50. Slayer Tower / Catacombs.',
    flavorText: 'Best HP/XP in the Slayer Tower. The bot heals itself on hits. The bot is, in fact, vampiric.',
  },
  slayer_aberrant_spectres: {
    id: 'slayer_aberrant_spectres', name: 'Slayer — Aberrant Spectres', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { slayer: 60, attack: 65, defence: 60 },
    gpPerHour: 35000, suspicionPerHour: 3.3,
    baseDetectionRatePerTick: 0.0016,
    xpPerHour: { slayer: 26000, attack: 24000, defence: 20000 },
    unlockCost: 18000, teamSize: 1,
    unlockDescription: 'Requires Members + Slayer 60. Nose peg required (auto-equipped).',
    flavorText: 'They smell like death. The bot has no nose. Or shame.',
  },
  slayer_dust_devils: {
    id: 'slayer_dust_devils', name: 'Slayer — Dust Devils', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { slayer: 65, attack: 70, defence: 65 },
    gpPerHour: 38000, suspicionPerHour: 3.5,
    baseDetectionRatePerTick: 0.0017,
    xpPerHour: { slayer: 32000, attack: 28000, defence: 22000 },
    unlockCost: 22000, teamSize: 1,
    unlockDescription: 'Requires Members + Slayer 65. Catacombs of Kourend — burst stack.',
    flavorText: 'Battlestaff and mystic drops. The bot bursts a 9-stack. Detection +20%.',
  },
  slayer_kurasks: {
    id: 'slayer_kurasks', name: 'Slayer — Kurasks', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { slayer: 70, ranged: 70, strength: 65 },
    gpPerHour: 38000, suspicionPerHour: 3.4,
    baseDetectionRatePerTick: 0.0017,
    xpPerHour: { slayer: 30000, ranged: 32000 },
    unlockCost: 24000, teamSize: 1,
    unlockDescription: 'Requires Members + Slayer 70. Leaf-bladed weapons / broad arrows.',
    flavorText: 'Herb drops. Big alch fodder. The bot sees green and clicks faster.',
  },
  slayer_gargoyles: {
    id: 'slayer_gargoyles', name: 'Slayer — Gargoyles', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { slayer: 75, attack: 75, strength: 75 },
    gpPerHour: 42000, suspicionPerHour: 3.5,
    baseDetectionRatePerTick: 0.0018,
    xpPerHour: { slayer: 38000, attack: 35000, strength: 35000 },
    unlockCost: 28000, teamSize: 1,
    unlockDescription: 'Requires Members + Slayer 75. Rock hammer auto-equipped for the finisher.',
    flavorText: 'The bot scripts the rock hammer finisher to the millisecond. No human is that precise.',
  },
  slayer_nechryael: {
    id: 'slayer_nechryael', name: 'Slayer — Nechryael', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { slayer: 80, attack: 80, defence: 75, magic: 70 },
    gpPerHour: 44000, suspicionPerHour: 3.6,
    baseDetectionRatePerTick: 0.0018,
    xpPerHour: { slayer: 42000, attack: 38000, magic: 18000 },
    unlockCost: 32000, teamSize: 1,
    unlockDescription: 'Requires Members + Slayer 80. Catacombs of Kourend.',
    flavorText: 'Death runes drop in stacks of 50. The script sells them every 200 kills. Like clockwork.',
  },

  // ─── Tier 2 — Members Bosses ────────────────────────────────────────────────
  boss_obor: {
    id: 'boss_obor', name: 'Boss — Obor (Hill Titan)', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { attack: 60, strength: 60, defence: 55 },
    gpPerHour: 22000, suspicionPerHour: 2.4,
    baseDetectionRatePerTick: 0.0012,
    xpPerHour: { attack: 18000, strength: 18000, defence: 14000 },
    unlockCost: 8000, teamSize: 1,
    unlockDescription: 'Requires Members + Combat 60+. Edgeville Dungeon hill giant boss.',
    flavorText: 'Six giant keys to summon him. The bot farms hill giants for the keys. Vertical integration.',
  },
  boss_giant_mole: {
    id: 'boss_giant_mole', name: 'Boss — Giant Mole', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { attack: 65, strength: 65, defence: 60 },
    gpPerHour: 28000, suspicionPerHour: 2.6,
    baseDetectionRatePerTick: 0.0013,
    xpPerHour: { attack: 24000, strength: 24000, defence: 18000 },
    unlockCost: 12000, teamSize: 1,
    unlockDescription: 'Requires Members + Combat 65+. Falador Park entry.',
    flavorText: 'The mole burrows. The bot follows. The bot has the dig site memorised.',
  },
  boss_sarachnis: {
    id: 'boss_sarachnis', name: 'Boss — Sarachnis', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { attack: 70, strength: 70, defence: 70, prayer: 43 },
    gpPerHour: 36000, suspicionPerHour: 2.9,
    baseDetectionRatePerTick: 0.0014,
    xpPerHour: { attack: 30000, strength: 30000, defence: 24000 },
    unlockCost: 18000, teamSize: 1,
    unlockDescription: 'Requires Members + Combat 70+. Forthos Dungeon spider matriarch.',
    flavorText: 'Switches melee and ranged attacks. The bot switches prayers tick-perfectly. Always.',
  },
  boss_kbd: {
    id: 'boss_kbd', name: 'Boss — King Black Dragon', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { attack: 80, strength: 80, defence: 75, ranged: 75, hitpoints: 75 },
    gpPerHour: 38000, suspicionPerHour: 3.0,
    baseDetectionRatePerTick: 0.0015,
    xpPerHour: { attack: 32000, strength: 32000, defence: 26000 },
    unlockCost: 25000, teamSize: 1,
    unlockDescription: 'Requires Members + Combat 80+. Wilderness lair, anti-dragon shield required.',
    flavorText: 'Three heads. Three breath weapons. The bot has the prayer flick down. The bot dies sometimes anyway.',
  },
  boss_barrows: {
    id: 'boss_barrows', name: 'Boss — Barrows Brothers', tier: 2,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { attack: 70, strength: 70, defence: 70, magic: 70, prayer: 43 },
    gpPerHour: 33000, suspicionPerHour: 2.7,
    baseDetectionRatePerTick: 0.0014,
    xpPerHour: { attack: 22000, strength: 22000, defence: 18000, magic: 14000 },
    unlockCost: 20000, teamSize: 1,
    unlockDescription: 'Requires Members + Combat 70+ + Magic 70 + Prayer 43.',
    flavorText: 'Six brothers, six tombs, one chest. The bot has the prayer puzzle script optimised. RNG still rules.',
  },

  // ─── Tier 3 — Late Game ─────────────────────────────────────────────────────
  zulrah: {
    id: 'zulrah', name: 'Zulrah', tier: 3,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { magic: 75, ranged: 75, hitpoints: 70 },
    gpPerHour: 120000, suspicionPerHour: 6.0,
    baseDetectionRatePerTick: 0.0035,
    xpPerHour: { magic: 30000, ranged: 20000 },
    unlockCost: 50000, teamSize: 1,
    unlockDescription: 'Requires Members + Magic 75 + Ranged 75. Zulrah Script highly recommended.',
    flavorText: 'The snake boss that prints gold. Jagex has a special detector for Zulrah bots.',
  },
  vorkath: {
    id: 'vorkath', name: 'Vorkath', tier: 3,
    requiresMembers: true, requiresPremium: true,
    skillRequirements: { ranged: 85, hitpoints: 80, magic: 65 },
    gpPerHour: 160000, suspicionPerHour: 6.5,
    baseDetectionRatePerTick: 0.0040,
    xpPerHour: { ranged: 35000 },
    unlockCost: 75000, teamSize: 1,
    unlockDescription: 'Requires Premium Members + Ranged 85. The best single-target gold farm.',
    flavorText: 'After Recipe for Disaster. Your bot somehow completed all the quests. Interesting.',
  },
  high_alching: {
    id: 'high_alching', name: 'High Alchemy', tier: 3,
    requiresMembers: true, requiresPremium: false,
    skillRequirements: { magic: 55 },
    gpPerHour: 45000, suspicionPerHour: 4.0,
    baseDetectionRatePerTick: 0.0020,
    xpPerHour: { magic: 78000 },
    unlockCost: 30000, teamSize: 1,
    unlockDescription: 'Requires Members + Magic 55. Low risk, consistent gold.',
    flavorText: 'Click. Alch. Click. Alch. One click per 3 seconds for hours. Very human.',
  },
  chambers_of_xeric: {
    id: 'chambers_of_xeric', name: 'Chambers of Xeric (Solo)', tier: 3,
    requiresMembers: true, requiresPremium: true,
    skillRequirements: { attack: 90, strength: 90, defence: 85, magic: 80, ranged: 85 },
    gpPerHour: 200000, suspicionPerHour: 7.0,
    baseDetectionRatePerTick: 0.0045,
    xpPerHour: { attack: 40000, strength: 40000, magic: 25000 },
    unlockCost: 150000, teamSize: 1,
    unlockDescription: 'Requires Premium Members + Combat 90+. Raid bot. Extremely profitable.',
    flavorText: 'A bot soloing CoX. No one believes it\'s human. No one is reporting it fast enough.',
  },

  // ─── Tier 4 — Endgame Raids ─────────────────────────────────────────────────
  tombs_of_amascut: {
    id: 'tombs_of_amascut', name: 'Tombs of Amascut', tier: 4,
    requiresMembers: true, requiresPremium: true,
    skillRequirements: { attack: 90, strength: 90, defence: 90, magic: 85, ranged: 90 },
    gpPerHour: 200000, // per bot, 600k total for 3-bot team
    suspicionPerHour: 3.0, // per bot (9.0 combined)
    baseDetectionRatePerTick: 0.0050,
    xpPerHour: { attack: 50000, strength: 50000, magic: 30000 },
    unlockCost: 500000, teamSize: 3,
    unlockDescription: 'Requires 3 Premium bots at Combat 90+. Team raid. 600k GP/hr total.',
    flavorText: 'Three bots perfectly synchronised. Tobias Jagex doesn\'t sleep. Neither do you.',
  },
  theatre_of_blood: {
    id: 'theatre_of_blood', name: 'Theatre of Blood', tier: 4,
    requiresMembers: true, requiresPremium: true,
    skillRequirements: { attack: 100, strength: 100, defence: 95, magic: 90, ranged: 95 },
    gpPerHour: 240000, // per bot, 1.2m total for 5-bot team
    suspicionPerHour: 2.4, // per bot (12.0 combined)
    baseDetectionRatePerTick: 0.0060,
    xpPerHour: { attack: 60000, strength: 60000 },
    unlockCost: 1500000, teamSize: 5,
    unlockDescription: 'Requires 5 Premium bots at Combat 100+. The ultimate bot farm.',
    flavorText: 'A coordinated ToB team of bots. The economy cries. You smile.',
  },
};

export const TIER_1_ACTIVITIES = Object.values(ACTIVITIES).filter(a => a.tier === 1).map(a => a.id);
export const TIER_2_ACTIVITIES = Object.values(ACTIVITIES).filter(a => a.tier === 2).map(a => a.id);
export const TIER_3_ACTIVITIES = Object.values(ACTIVITIES).filter(a => a.tier === 3).map(a => a.id);
export const TIER_4_ACTIVITIES = Object.values(ACTIVITIES).filter(a => a.tier === 4).map(a => a.id);

// All free Tier 1 activities are default-unlocked. The activity picker still
// hides any whose skill requirements the bot hasn't met yet, so this just makes
// every free activity reachable without an extra "unlock" step in the UI.
export const DEFAULT_UNLOCKED_ACTIVITIES: ActivityId[] = [
  // Woodcutting
  'wc_trees', 'wc_oaks', 'wc_willows', 'wc_maples', 'wc_yews',
  // Fishing
  'fish_shrimp', 'fish_sardines', 'fish_anchovies', 'fish_trout_salmon',
  'fish_lobsters', 'fish_bass', 'fish_tuna_swordfish', 'fish_sharks',
  // Mining
  'mine_tin', 'mine_clay', 'mine_rune_essence', 'mine_iron', 'mine_silver',
  'mine_coal', 'mine_gold', 'mine_mithril', 'mine_adamantite', 'mine_runite_wilderness',
  // Smithing
  'smith_bronze_bars', 'smith_iron_bars', 'smith_steel_bars', 'smith_gold_bars',
  'smith_iron_platebodies', 'smith_mithril_bars', 'smith_adamant_bars',
  // Runecrafting
  'rc_air_runes', 'rc_mind_runes', 'rc_water_runes', 'rc_earth_runes',
  'rc_fire_runes', 'rc_body_runes',
  // Magic
  'magic_low_alch', 'magic_telegrab_wines', 'magic_high_alch_plates',
  // Production / Misc
  'tan_cowhides', 'stronghold_clearout',
  // Combat
  'combat_chickens', 'combat_giant_rats', 'combat_men', 'combat_monks',
  'combat_goblins', 'combat_giant_frogs', 'combat_cows', 'combat_imps',
  'combat_minotaurs', 'combat_dark_wizards', 'combat_flesh_crawlers',
  'combat_zombies', 'combat_skeletons', 'combat_giant_spiders',
  'combat_hobgoblins', 'combat_hill_giants', 'combat_black_knights',
  'combat_ankou', 'combat_lesser_demons',
];

// GP/hr displayed (adjusts for team size where GP is per-bot already)
export function getActivityGpHr(activity: Activity): number {
  return activity.gpPerHour * activity.teamSize;
}
